file_path = 'alembic/versions/476568fc3a70_add_github_integration_models.py'
with open(file_path, 'r') as f:
    content = f.read()

content = content.replace("def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###", "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n    op.execute('TRUNCATE TABLE pull_request, repository, webhook_event CASCADE')")

with open(file_path, 'w') as f:
    f.write(content)
