"""Update finding schema

Revision ID: 18af049af059
Revises: 2426528e6df4
Create Date: 2026-10-01 16:11:08.149871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18af049af059'
down_revision: Union[str, None] = '2426528e6df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('review_dimension', sa.String(length=100), nullable=True))
    op.add_column('finding', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('impact', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('evidence_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('finding', sa.Column('finding_fingerprint', sa.String(length=255), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('finding', 'finding_fingerprint')
    op.drop_column('finding', 'evidence_sources')
    op.drop_column('finding', 'impact')
    op.drop_column('finding', 'reasoning')
    op.drop_column('finding', 'review_dimension')
    # ### end Alembic commands ###
