"""Actually add review_run schema

Revision ID: 1f13f692463e
Revises: a3f76648b853
Create Date: 2026-09-23 16:52:04.232885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f13f692463e'
down_revision: Union[str, None] = 'a3f76648b853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('repomind_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('intelligence_mode', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_run_id'), 'review_run', ['id'], unique=False)
    op.create_index(op.f('ix_review_run_pull_request_id'), 'review_run', ['pull_request_id'], unique=False)
    op.create_table('conflict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_id'), 'conflict', ['id'], unique=False)
    op.create_index(op.f('ix_conflict_review_run_id'), 'conflict', ['review_run_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('rule_source', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_id'), 'finding', ['id'], unique=False)
    op.create_index(op.f('ix_finding_review_run_id'), 'finding', ['review_run_id'], unique=False)
    op.create_table('human_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_decision_id'), 'human_decision', ['id'], unique=False)
    op.create_index(op.f('ix_human_decision_review_run_id'), 'human_decision', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_human_decision_user_id'), 'human_decision', ['user_id'], unique=False)
    op.create_table('linter_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linter_result_id'), 'linter_result', ['id'], unique=False)
    op.create_index(op.f('ix_linter_result_review_run_id'), 'linter_result', ['review_run_id'], unique=False)
    op.create_table('risk_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blast_radius', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_id'), 'risk_assessment', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_review_run_id'), 'risk_assessment', ['review_run_id'], unique=True)
    op.create_table('finding_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('citation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_id'), 'finding_evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_evidence_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_risk_assessment_review_run_id'), table_name='risk_assessment')
    op.drop_index(op.f('ix_risk_assessment_id'), table_name='risk_assessment')
    op.drop_table('risk_assessment')
    op.drop_index(op.f('ix_linter_result_review_run_id'), table_name='linter_result')
    op.drop_index(op.f('ix_linter_result_id'), table_name='linter_result')
    op.drop_table('linter_result')
    op.drop_index(op.f('ix_human_decision_user_id'), table_name='human_decision')
    op.drop_index(op.f('ix_human_decision_review_run_id'), table_name='human_decision')
    op.drop_index(op.f('ix_human_decision_id'), table_name='human_decision')
    op.drop_table('human_decision')
    op.drop_index(op.f('ix_finding_review_run_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_conflict_review_run_id'), table_name='conflict')
    op.drop_index(op.f('ix_conflict_id'), table_name='conflict')
    op.drop_table('conflict')
    op.drop_index(op.f('ix_review_run_pull_request_id'), table_name='review_run')
    op.drop_index(op.f('ix_review_run_id'), table_name='review_run')
    op.drop_table('review_run')
    # ### end Alembic commands ###
