"""Add GithubConnection table

Revision ID: 39482a492cd9
Revises: cd8a43834a0f
Create Date: 2026-09-24 14:45:11.566795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39482a492cd9'
down_revision: Union[str, None] = 'cd8a43834a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_token', sa.String(length=1024), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connection_id'), 'github_connection', ['id'], unique=False)
    op.create_index(op.f('ix_github_connection_organization_id'), 'github_connection', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_connection_organization_id'), table_name='github_connection')
    op.drop_index(op.f('ix_github_connection_id'), table_name='github_connection')
    op.drop_table('github_connection')
    # ### end Alembic commands ###
