"""Add GitHub integration models

Revision ID: 476568fc3a70
Revises: 9ebe0b6eb803
Create Date: 2026-09-23 16:00:51.604626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '476568fc3a70'
down_revision: Union[str, None] = '9ebe0b6eb803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE pull_request, repository, webhook_event CASCADE')
    op.create_table('github_identity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_user_id', sa.String(length=255), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_identity_github_user_id'), 'github_identity', ['github_user_id'], unique=True)
    op.create_index(op.f('ix_github_identity_id'), 'github_identity', ['id'], unique=False)
    op.create_index(op.f('ix_github_identity_user_id'), 'github_identity', ['user_id'], unique=True)
    op.create_table('github_credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_identity_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=1024), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['github_identity_id'], ['github_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_credential_github_identity_id'), 'github_credential', ['github_identity_id'], unique=True)
    op.create_index(op.f('ix_github_credential_id'), 'github_credential', ['id'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', 'org_owner', 'eng_manager', 'tech_lead', 'security_reviewer', 'read_only', name='roleenum', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_member_id'), 'project_member', ['id'], unique=False)
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_user_id'), 'project_member', ['user_id'], unique=False)
    op.create_table('project_merge_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('require_human_approval', sa.Integer(), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=True),
    sa.Column('require_ai_analysis', sa.Integer(), nullable=True),
    sa.Column('require_ci_success', sa.Integer(), nullable=True),
    sa.Column('auto_merge_enabled', sa.Integer(), nullable=True),
    sa.Column('approval_validity', sa.String(length=100), nullable=True),
    sa.Column('require_latest_commit_review', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_merge_policy_id'), 'project_merge_policy', ['id'], unique=False)
    op.create_index(op.f('ix_project_merge_policy_project_id'), 'project_merge_policy', ['project_id'], unique=True)
    op.create_table('github_repository_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_identity_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['github_identity_id'], ['github_identity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_identity_id', 'repository_id', name='uq_github_repo_access')
    )
    op.create_index(op.f('ix_github_repository_access_github_identity_id'), 'github_repository_access', ['github_identity_id'], unique=False)
    op.create_index(op.f('ix_github_repository_access_id'), 'github_repository_access', ['id'], unique=False)
    op.create_index(op.f('ix_github_repository_access_repository_id'), 'github_repository_access', ['repository_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_commit_sha'), 'ai_analysis', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_ai_analysis_id'), 'ai_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_pull_request_id'), 'ai_analysis', ['pull_request_id'], unique=False)
    op.create_table('automation_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('github_identity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('github_resource_id', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('expected_head_sha', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['github_identity_id'], ['github_identity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_automation_action_id'), 'automation_action', ['id'], unique=False)
    op.create_index(op.f('ix_automation_action_organization_id'), 'automation_action', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_action_project_id'), 'automation_action', ['project_id'], unique=False)
    op.create_index(op.f('ix_automation_action_pull_request_id'), 'automation_action', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_automation_action_repository_id'), 'automation_action', ['repository_id'], unique=False)
    op.create_table('github_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_comment_id', sa.String(length=255), nullable=False),
    sa.Column('github_author_login', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_comment_github_comment_id'), 'github_comment', ['github_comment_id'], unique=True)
    op.create_index(op.f('ix_github_comment_id'), 'github_comment', ['id'], unique=False)
    op.create_index(op.f('ix_github_comment_pull_request_id'), 'github_comment', ['pull_request_id'], unique=False)
    op.create_table('github_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_review_id', sa.String(length=255), nullable=False),
    sa.Column('github_reviewer_login', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synchronization_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_review_github_review_id'), 'github_review', ['github_review_id'], unique=True)
    op.create_index(op.f('ix_github_review_id'), 'github_review', ['id'], unique=False)
    op.create_index(op.f('ix_github_review_pull_request_id'), 'github_review', ['pull_request_id'], unique=False)
    op.create_table('human_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_commit_sha'), 'human_review', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_human_review_id'), 'human_review', ['id'], unique=False)
    op.create_index(op.f('ix_human_review_pull_request_id'), 'human_review', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_human_review_reviewer_id'), 'human_review', ['reviewer_id'], unique=False)
    op.create_table('pull_request_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('github_check_run_id', sa.String(length=255), nullable=False),
    sa.Column('check_suite_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('head_sha', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_check_github_check_run_id'), 'pull_request_check', ['github_check_run_id'], unique=True)
    op.create_index(op.f('ix_pull_request_check_id'), 'pull_request_check', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_check_pull_request_id'), 'pull_request_check', ['pull_request_id'], unique=False)
    op.create_table('pull_request_commit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('committer', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('parent_shas', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(length=1024), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_commit_id'), 'pull_request_commit', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_commit_pull_request_id'), 'pull_request_commit', ['pull_request_id'], unique=False)
    op.create_table('pull_request_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('actor_login', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_event_id'), 'pull_request_event', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_event_pull_request_id'), 'pull_request_event', ['pull_request_id'], unique=False)
    op.create_table('pull_request_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Integer(), nullable=True),
    sa.Column('previous_filename', sa.String(length=1024), nullable=True),
    sa.Column('blob_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_url', sa.String(length=1024), nullable=True),
    sa.Column('patch_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_file_id'), 'pull_request_file', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_file_pull_request_id'), 'pull_request_file', ['pull_request_id'], unique=False)
    op.drop_index('ix_ml_prediction_id', table_name='ml_prediction')
    op.drop_index('ix_ml_prediction_pull_request_id', table_name='ml_prediction')
    op.execute("DROP TABLE IF EXISTS ml_prediction CASCADE")
    op.drop_index('ix_chat_session_id', table_name='chat_session')
    op.drop_index('ix_chat_session_organization_id', table_name='chat_session')
    op.drop_index('ix_chat_session_user_id', table_name='chat_session')
    op.execute("DROP TABLE IF EXISTS chat_session CASCADE")
    op.drop_index('ix_commit_id', table_name='commit')
    op.drop_index('ix_commit_pull_request_id', table_name='commit')
    op.execute("DROP TABLE IF EXISTS commit CASCADE")
    op.drop_index('ix_review_run_id', table_name='review_run')
    op.drop_index('ix_review_run_pull_request_id', table_name='review_run')
    op.execute("DROP TABLE IF EXISTS review_run CASCADE")
    op.drop_index('ix_conflict_id', table_name='conflict')
    op.drop_index('ix_conflict_review_run_id', table_name='conflict')
    op.execute("DROP TABLE IF EXISTS conflict CASCADE")
    op.drop_index('ix_finding_id', table_name='finding')
    op.drop_index('ix_finding_review_run_id', table_name='finding')
    op.execute("DROP TABLE IF EXISTS finding CASCADE")
    op.drop_index('ix_risk_assessment_id', table_name='risk_assessment')
    op.drop_index('ix_risk_assessment_review_run_id', table_name='risk_assessment')
    op.execute("DROP TABLE IF EXISTS risk_assessment CASCADE")
    op.drop_index('ix_human_decision_id', table_name='human_decision')
    op.drop_index('ix_human_decision_review_run_id', table_name='human_decision')
    op.drop_index('ix_human_decision_user_id', table_name='human_decision')
    op.execute("DROP TABLE IF EXISTS human_decision CASCADE")
    op.drop_index('ix_github_connection_id', table_name='github_connection')
    op.drop_index('ix_github_connection_organization_id', table_name='github_connection')
    op.execute("DROP TABLE IF EXISTS github_connection CASCADE")
    op.drop_index('ix_chat_message_id', table_name='chat_message')
    op.drop_index('ix_chat_message_session_id', table_name='chat_message')
    op.execute("DROP TABLE IF EXISTS chat_message CASCADE")
    op.drop_index('ix_finding_evidence_finding_id', table_name='finding_evidence')
    op.drop_index('ix_finding_evidence_id', table_name='finding_evidence')
    op.execute("DROP TABLE IF EXISTS finding_evidence CASCADE")
    op.drop_index('ix_linter_result_id', table_name='linter_result')
    op.drop_index('ix_linter_result_review_run_id', table_name='linter_result')
    op.execute("DROP TABLE IF EXISTS linter_result CASCADE")
    op.alter_column('organization_membership', 'role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', 'org_owner', 'eng_manager', 'tech_lead', 'security_reviewer', 'read_only', name='roleenum', native_enum=False),
               existing_nullable=False)
    op.add_column('pull_request', sa.Column('github_pr_id', sa.String(length=255), nullable=False, server_default='legacy'))
    op.add_column('pull_request', sa.Column('github_url', sa.String(length=1024), nullable=True))
    op.add_column('pull_request', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pull_request', sa.Column('author_user_id', sa.Integer(), nullable=True))
    op.add_column('pull_request', sa.Column('github_author_login', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('source_branch', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('target_branch', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('base_sha', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('draft_status', sa.Integer(), nullable=True))
    op.add_column('pull_request', sa.Column('mergeable_state', sa.String(length=50), nullable=True))
    op.add_column('pull_request', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pull_request', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pull_request', sa.Column('merged_by', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('merge_commit_sha', sa.String(length=255), nullable=True))
    op.add_column('pull_request', sa.Column('synchronization_status', sa.String(length=50), nullable=True))
    op.add_column('pull_request', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_pull_request_github_pr_id'), 'pull_request', ['github_pr_id'], unique=True)
    op.create_foreign_key(None, 'pull_request', 'user', ['author_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pull_request', 'author')
    op.drop_column('pull_request', 'additions')
    op.drop_column('pull_request', 'files_changed')
    op.drop_column('pull_request', 'deletions')
    op.add_column('repository', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('repository', sa.Column('github_repository_id', sa.String(length=255), nullable=False, server_default='legacy'))
    op.add_column('repository', sa.Column('github_url', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_repository_github_repository_id'), 'repository', ['github_repository_id'], unique=True)
    op.add_column('webhook_event', sa.Column('processed', sa.Integer(), nullable=True))
    op.add_column('webhook_event', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('webhook_event', 'github_delivery_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('webhook_event', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_webhook_event_received_at', table_name='webhook_event')
    op.drop_constraint('webhook_event_repository_id_fkey', 'webhook_event', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_event', 'repository', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_column('webhook_event', 'received_at')
    op.drop_column('webhook_event', 'error_message')
    op.drop_column('webhook_event', 'status')
    op.drop_column('webhook_event', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_event', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('webhook_event', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'received'::character varying"), autoincrement=False, nullable=False))
    op.add_column('webhook_event', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('webhook_event', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'webhook_event', type_='foreignkey')
    op.create_foreign_key('webhook_event_repository_id_fkey', 'webhook_event', 'repository', ['repository_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_webhook_event_received_at', 'webhook_event', ['received_at'], unique=False)
    op.alter_column('webhook_event', 'payload',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('webhook_event', 'github_delivery_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('webhook_event', 'created_at')
    op.drop_column('webhook_event', 'processed')
    op.drop_index(op.f('ix_repository_github_repository_id'), table_name='repository')
    op.drop_column('repository', 'github_url')
    op.drop_column('repository', 'github_repository_id')
    op.drop_column('repository', 'provider')
    op.add_column('pull_request', sa.Column('deletions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_request', sa.Column('files_changed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_request', sa.Column('additions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_request', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pull_request', type_='foreignkey')
    op.drop_index(op.f('ix_pull_request_github_pr_id'), table_name='pull_request')
    op.drop_column('pull_request', 'last_synced_at')
    op.drop_column('pull_request', 'synchronization_status')
    op.drop_column('pull_request', 'merge_commit_sha')
    op.drop_column('pull_request', 'merged_by')
    op.drop_column('pull_request', 'closed_at')
    op.drop_column('pull_request', 'updated_at')
    op.drop_column('pull_request', 'mergeable_state')
    op.drop_column('pull_request', 'draft_status')
    op.drop_column('pull_request', 'base_sha')
    op.drop_column('pull_request', 'target_branch')
    op.drop_column('pull_request', 'source_branch')
    op.drop_column('pull_request', 'github_author_login')
    op.drop_column('pull_request', 'author_user_id')
    op.drop_column('pull_request', 'description')
    op.drop_column('pull_request', 'github_url')
    op.drop_column('pull_request', 'github_pr_id')
    op.alter_column('organization_membership', 'role',
               existing_type=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', 'org_owner', 'eng_manager', 'tech_lead', 'security_reviewer', 'read_only', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.create_table('linter_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], name='linter_result_review_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='linter_result_pkey')
    )
    op.create_index('ix_linter_result_review_run_id', 'linter_result', ['review_run_id'], unique=False)
    op.create_index('ix_linter_result_id', 'linter_result', ['id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_status', sa.VARCHAR(length=50), server_default=sa.text("'unverified'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('citation_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name='finding_evidence_finding_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='finding_evidence_pkey')
    )
    op.create_index('ix_finding_evidence_id', 'finding_evidence', ['id'], unique=False)
    op.create_index('ix_finding_evidence_finding_id', 'finding_evidence', ['finding_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_grounded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name='chat_message_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_message_pkey')
    )
    op.create_index('ix_chat_message_session_id', 'chat_message', ['session_id'], unique=False)
    op.create_index('ix_chat_message_id', 'chat_message', ['id'], unique=False)
    op.create_table('github_connection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('encrypted_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='github_connection_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='github_connection_pkey')
    )
    op.create_index('ix_github_connection_organization_id', 'github_connection', ['organization_id'], unique=False)
    op.create_index('ix_github_connection_id', 'github_connection', ['id'], unique=False)
    op.create_table('human_decision',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], name='human_decision_review_run_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='human_decision_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='human_decision_pkey')
    )
    op.create_index('ix_human_decision_user_id', 'human_decision', ['user_id'], unique=False)
    op.create_index('ix_human_decision_review_run_id', 'human_decision', ['review_run_id'], unique=False)
    op.create_index('ix_human_decision_id', 'human_decision', ['id'], unique=False)
    op.create_table('risk_assessment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), server_default=sa.text("'low'::character varying"), autoincrement=False, nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blast_radius', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('test_impact', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], name='risk_assessment_review_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='risk_assessment_pkey'),
    sa.UniqueConstraint('review_run_id', name='uq_risk_assessment_review_run')
    )
    op.create_index('ix_risk_assessment_review_run_id', 'risk_assessment', ['review_run_id'], unique=False)
    op.create_index('ix_risk_assessment_id', 'risk_assessment', ['id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rule_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('evidence_status', sa.VARCHAR(length=50), server_default=sa.text("'unverified'::character varying"), autoincrement=False, nullable=True),
    sa.Column('lifecycle_status', sa.VARCHAR(length=50), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], name='finding_review_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='finding_pkey')
    )
    op.create_index('ix_finding_review_run_id', 'finding', ['review_run_id'], unique=False)
    op.create_index('ix_finding_id', 'finding', ['id'], unique=False)
    op.create_table('conflict',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conflict_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_run.id'], name='conflict_review_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conflict_pkey')
    )
    op.create_index('ix_conflict_review_run_id', 'conflict', ['review_run_id'], unique=False)
    op.create_index('ix_conflict_id', 'conflict', ['id'], unique=False)
    op.create_table('review_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to pull_request.id; CASCADE on delete.'),
    sa.Column('commit_sha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('repomind_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rag_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('intelligence_mode', sa.VARCHAR(length=20), server_default=sa.text("'v1'::character varying"), autoincrement=False, nullable=True),
    sa.Column('progress_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], name='review_run_pull_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='review_run_pkey')
    )
    op.create_index('ix_review_run_pull_request_id', 'review_run', ['pull_request_id'], unique=False)
    op.create_index('ix_review_run_id', 'review_run', ['id'], unique=False)
    op.create_table('commit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], name='commit_pull_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='commit_pkey')
    )
    op.create_index('ix_commit_pull_request_id', 'commit', ['pull_request_id'], unique=False)
    op.create_index('ix_commit_id', 'commit', ['id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='chat_session_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_session_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_session_pkey')
    )
    op.create_index('ix_chat_session_user_id', 'chat_session', ['user_id'], unique=False)
    op.create_index('ix_chat_session_organization_id', 'chat_session', ['organization_id'], unique=False)
    op.create_index('ix_chat_session_id', 'chat_session', ['id'], unique=False)
    op.create_table('ml_prediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_delay_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prediction_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], name='ml_prediction_pull_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ml_prediction_pkey')
    )
    op.create_index('ix_ml_prediction_pull_request_id', 'ml_prediction', ['pull_request_id'], unique=True)
    op.create_index('ix_ml_prediction_id', 'ml_prediction', ['id'], unique=False)
    op.drop_index(op.f('ix_pull_request_file_pull_request_id'), table_name='pull_request_file')
    op.drop_index(op.f('ix_pull_request_file_id'), table_name='pull_request_file')
    op.execute("DROP TABLE IF EXISTS pull_request_file CASCADE")
    op.drop_index(op.f('ix_pull_request_event_pull_request_id'), table_name='pull_request_event')
    op.drop_index(op.f('ix_pull_request_event_id'), table_name='pull_request_event')
    op.execute("DROP TABLE IF EXISTS pull_request_event CASCADE")
    op.drop_index(op.f('ix_pull_request_commit_pull_request_id'), table_name='pull_request_commit')
    op.drop_index(op.f('ix_pull_request_commit_id'), table_name='pull_request_commit')
    op.execute("DROP TABLE IF EXISTS pull_request_commit CASCADE")
    op.drop_index(op.f('ix_pull_request_check_pull_request_id'), table_name='pull_request_check')
    op.drop_index(op.f('ix_pull_request_check_id'), table_name='pull_request_check')
    op.drop_index(op.f('ix_pull_request_check_github_check_run_id'), table_name='pull_request_check')
    op.execute("DROP TABLE IF EXISTS pull_request_check CASCADE")
    op.drop_index(op.f('ix_human_review_reviewer_id'), table_name='human_review')
    op.drop_index(op.f('ix_human_review_pull_request_id'), table_name='human_review')
    op.drop_index(op.f('ix_human_review_id'), table_name='human_review')
    op.drop_index(op.f('ix_human_review_commit_sha'), table_name='human_review')
    op.execute("DROP TABLE IF EXISTS human_review CASCADE")
    op.drop_index(op.f('ix_github_review_pull_request_id'), table_name='github_review')
    op.drop_index(op.f('ix_github_review_id'), table_name='github_review')
    op.drop_index(op.f('ix_github_review_github_review_id'), table_name='github_review')
    op.execute("DROP TABLE IF EXISTS github_review CASCADE")
    op.drop_index(op.f('ix_github_comment_pull_request_id'), table_name='github_comment')
    op.drop_index(op.f('ix_github_comment_id'), table_name='github_comment')
    op.drop_index(op.f('ix_github_comment_github_comment_id'), table_name='github_comment')
    op.execute("DROP TABLE IF EXISTS github_comment CASCADE")
    op.drop_index(op.f('ix_automation_action_repository_id'), table_name='automation_action')
    op.drop_index(op.f('ix_automation_action_pull_request_id'), table_name='automation_action')
    op.drop_index(op.f('ix_automation_action_project_id'), table_name='automation_action')
    op.drop_index(op.f('ix_automation_action_organization_id'), table_name='automation_action')
    op.drop_index(op.f('ix_automation_action_id'), table_name='automation_action')
    op.execute("DROP TABLE IF EXISTS automation_action CASCADE")
    op.drop_index(op.f('ix_ai_analysis_pull_request_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_commit_sha'), table_name='ai_analysis')
    op.execute("DROP TABLE IF EXISTS ai_analysis CASCADE")
    op.drop_index(op.f('ix_github_repository_access_repository_id'), table_name='github_repository_access')
    op.drop_index(op.f('ix_github_repository_access_id'), table_name='github_repository_access')
    op.drop_index(op.f('ix_github_repository_access_github_identity_id'), table_name='github_repository_access')
    op.execute("DROP TABLE IF EXISTS github_repository_access CASCADE")
    op.drop_index(op.f('ix_project_merge_policy_project_id'), table_name='project_merge_policy')
    op.drop_index(op.f('ix_project_merge_policy_id'), table_name='project_merge_policy')
    op.execute("DROP TABLE IF EXISTS project_merge_policy CASCADE")
    op.drop_index(op.f('ix_project_member_user_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_id'), table_name='project_member')
    op.execute("DROP TABLE IF EXISTS project_member CASCADE")
    op.drop_index(op.f('ix_github_credential_id'), table_name='github_credential')
    op.drop_index(op.f('ix_github_credential_github_identity_id'), table_name='github_credential')
    op.execute("DROP TABLE IF EXISTS github_credential CASCADE")
    op.drop_index(op.f('ix_github_identity_user_id'), table_name='github_identity')
    op.drop_index(op.f('ix_github_identity_id'), table_name='github_identity')
    op.drop_index(op.f('ix_github_identity_github_user_id'), table_name='github_identity')
    op.execute("DROP TABLE IF EXISTS github_identity CASCADE")
    # ### end Alembic commands ###
