"""004_user_onboarding_fields

Revision ID: 6785debac2a0
Revises: f52225de5db9
Create Date: 2026-09-08 16:33:34.699688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6785debac2a0'
down_revision: Union[str, None] = 'f52225de5db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invitation_token_hash', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_user_invitation_token_hash'), 'user', ['invitation_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invitation_token_hash'), table_name='user')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'invitation_expires_at')
    op.drop_column('user', 'invitation_token_hash')
    # ### end Alembic commands ###
