"""sync_webhook_event_action

Revision ID: a29d00a3e5e1
Revises: cd8a43834a0f
Create Date: 2026-09-29 15:26:55.234594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a29d00a3e5e1'
down_revision: Union[str, None] = 'cd8a43834a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_message_id', table_name='chat_message')
    op.drop_index('ix_chat_message_session_id', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_commit_id', table_name='commit')
    op.drop_index('ix_commit_pull_request_id', table_name='commit')
    op.drop_table('commit')
    op.drop_index('ix_chat_session_id', table_name='chat_session')
    op.drop_index('ix_chat_session_organization_id', table_name='chat_session')
    op.drop_index('ix_chat_session_user_id', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('ix_ml_prediction_id', table_name='ml_prediction')
    op.drop_index('ix_ml_prediction_pull_request_id', table_name='ml_prediction')
    op.drop_table('ml_prediction')
    op.alter_column('organization_membership', 'role',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', name='roleenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('project_member', 'role',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', name='roleenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('review_run', 'pull_request_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to pull_request.id; CASCADE on delete.',
               existing_nullable=False)
    op.drop_constraint('uq_risk_assessment_review_run', 'risk_assessment', type_='unique')
    op.drop_index('ix_risk_assessment_review_run_id', table_name='risk_assessment')
    op.create_index(op.f('ix_risk_assessment_review_run_id'), 'risk_assessment', ['review_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessment_review_run_id'), table_name='risk_assessment')
    op.create_index('ix_risk_assessment_review_run_id', 'risk_assessment', ['review_run_id'], unique=False)
    op.create_unique_constraint('uq_risk_assessment_review_run', 'risk_assessment', ['review_run_id'])
    op.alter_column('review_run', 'pull_request_id',
               existing_type=sa.INTEGER(),
               comment='FK to pull_request.id; CASCADE on delete.',
               existing_nullable=False)
    op.alter_column('project_member', 'role',
               existing_type=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.alter_column('organization_membership', 'role',
               existing_type=sa.Enum('developer', 'reviewer', 'team_lead', 'org_admin', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.create_table('ml_prediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_delay_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prediction_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], name='ml_prediction_pull_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ml_prediction_pkey')
    )
    op.create_index('ix_ml_prediction_pull_request_id', 'ml_prediction', ['pull_request_id'], unique=True)
    op.create_index('ix_ml_prediction_id', 'ml_prediction', ['id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='chat_session_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_session_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_chat_session_user_id', 'chat_session', ['user_id'], unique=False)
    op.create_index('ix_chat_session_organization_id', 'chat_session', ['organization_id'], unique=False)
    op.create_index('ix_chat_session_id', 'chat_session', ['id'], unique=False)
    op.create_table('commit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], name='commit_pull_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='commit_pkey')
    )
    op.create_index('ix_commit_pull_request_id', 'commit', ['pull_request_id'], unique=False)
    op.create_index('ix_commit_id', 'commit', ['id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_grounded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name='chat_message_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_message_pkey')
    )
    op.create_index('ix_chat_message_session_id', 'chat_message', ['session_id'], unique=False)
    op.create_index('ix_chat_message_id', 'chat_message', ['id'], unique=False)
    # ### end Alembic commands ###
