"""native_pgvector

Revision ID: f2a7b8f58af8
Revises: bb220ed50f98
Create Date: 2026-09-11 12:11:04.151068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f2a7b8f58af8'
down_revision: Union[str, None] = 'bb220ed50f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("ALTER TABLE document_chunk ALTER COLUMN embedding TYPE vector(384) USING (embedding::text::vector)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE document_chunk ALTER COLUMN embedding TYPE jsonb USING (embedding::text::jsonb)")
    # ### end Alembic commands ###
